image: php:7-cli

before_script:
  - apt-get update -yqq
  - apt-get install git -yqq
  - curl --location --output /usr/local/bin/phpunit https://phar.phpunit.de/phpunit.phar
  - chmod +x /usr/local/bin/phpunit
  - curl --silent --show-error https://getcomposer.org/installer | php
  - php composer.phar install

test:app:
  script:
  - phpunit .

cache:
  paths:
  - vendor/