language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4snapshot'
  - nightly

env:
  matrix:
    - dependencies=lowest
    - dependencies=highest

matrix:
  allow_failures:
    - php: 'nightly'
    - php: '7.4snapshot'

install:
  - composer self-update
  - if [ -z "$dependencies" ]; then composer install -v; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -nv; fi;
  - if [ "$dependencies" = "highest" ]; then composer update -nv; fi;

script: composer check
