language: php

sudo: false

php:
  - '7.0'
  - '7.1'
  - nightly

before_install:
  - composer self-update

install: composer update --prefer-dist $COMPOSER_FLAGS

<<<<<<< HEAD
script: ./vendor/bin/phpqa --analyzedDirs src,tests && ./vendor/bin/phpunit --coverage-text
=======
script: phpunit --coverage-text
>>>>>>> e89dea459bd37ea1291944ea8ce2b8eeed31f97f
