language: php

sudo: false

php:
  - '7.0'
  - '7.1'
  - nightly

before_install:
  - composer self-update

install: composer update --prefer-dist $COMPOSER_FLAGS

script: ./vendor/bin/phpqa --analyzedDirs src,tests && ./vendor/bin/phpunit --coverage-text
